exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: "ecommerce_integrations.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: end-of-file-fixer
        files: "ecommerce_integrations.*"
        exclude: ".*json$|.*txt$"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]
      - id: ruff
        name: "Run ruff linter"
      - id: ruff-format
        name: "Run ruff formatter"

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
